Add option of RetainBigDiffFilesOnly to jit-analyze
dotnet/jitutils pull request #347
Opened 2021-11-16 23:46 UTC by kunalspathak

`RetainBigDiffFilesOnly` will make `jit-analyze` to delete the `.dasm` files and retain just the top `count` files that contains largest diffs. This will help us in reducing the `.dasm` files size when we upload them as part of CI. By default, this option is off and hence we will never delete those files.

Thoughts?

2021-11-16 23:46 UTC, kunalspathak commented
@BruceForstall - any thoughts?

2021-11-16 23:49 UTC, EgorBo approved these changes

2021-11-17 00:51 UTC, BruceForstall requested changes
The idea seems good. Some comments/suggestions:

1. We already have a list of the base/diff files (`baseList` / `diffList` in `Main`) in a FileInfo list, that includes the full path. Those paths are copied into the `FileDelta` structure. So it seems like we shouldn't do a directory search for files to delete, we should use the file paths we already have.
2. What if you initialize a member of FileInfo (or FileDelta), `retain = false`, only used if the `retain` option is used, set it to `true` in the `DisplayFileMetric` code, then simply iterate over the lists towards the end of `Main` deleting files where this is `false`?
3. Nit: name arg `-retainOnlyTopFiles` instead? Why? "Diff" implies it wouldn't delete "Base" files (which it would/should). "Top" implies the highest metric value, which might not be the "biggest". Maybe even more general: "-retainReportedFiles", meaning to retain any files on which we report a regression/improvement. We might choose to report both the largest, weighted, code size diffs. But we might also want to report the smallest, which are often the easiest to analyze. In fact, for the purpose of saving things in the CI, it would be quite useful to include both those sets.

2021-11-17 02:49 UTC, kunalspathak commented
Done.

2021-11-17 02:51 UTC, kunalspathak commented
Related PR where this option will be consumed - https://github.com/dotnet/runtime/pull/61700

2021-11-17 14:53 UTC, kunalspathak commented
> But we might also want to report the smallest, which are often the easiest to analyze. In fact, for the purpose of saving things in the CI, it would be quite useful to include both those sets.

I will keep that as a future improvement. Let us monitor and see how big the size of top (largest) subset is and if there is a need to see at smaller subset. I usually just pick the smallest of the top files that are reported.

2021-11-17 17:37 UTC, BruceForstall approved these changes

2021-11-17 17:37 UTC, BruceForstall commented on src/jit-analyze/jit-analyze.cs
> +                        "Retain only the .dasm files that has top 'count' improvements/regressions. Delete other files. Useful in CI scenario to reduce the upload size.");
grammar nit:
```suggestion
                        "Retain only the top 'count' improvements/regressions .dasm files. Delete other files. Useful in CI scenario to reduce the upload size.");
```

2021-11-17 17:39 UTC, merged